In [ ]:
# This notebook helps users to clean Ogimet files into pandas with TAFs
import pandas as pd
import re

def clean_taf_ogimet_file(file_path):
  cleaned_tafs = []

  with open(file_path, 'r') as f:
    text = f.read()

    # Use regular expressions to find all TAF forecasts
    # assume that there is YYYYMMDDHHMM pattern
    # - assume that  TAF is terminated by =
    taf_forecasts = re.findall(r'\d{12}.+?=', text, re.DOTALL)

    # Remove the junk data in between TAF forecasts and add to the list
    clean_taf_forecasts = [taf.strip() for taf in taf_forecasts]
    cleaned_tafs.extend(clean_taf_forecasts)

  # Create a DataFrame from the cleaned TAF forecasts list
  df = pd.DataFrame(cleaned_tafs, columns=['TAF Forecast'])

  return df

Example usage for all the files in the directory and concatenating them

In [26]:
#Original file
with open('/content/TAF202007.txt', 'r') as f:
    text = f.read()
print(text[:1000]) # print just part of it as we do not know the size

Display metars













##########################################################
# Query made at 07/20/2023 09:29:20 UTC
# Time interval: from 07/01/2020 00:00  to 07/31/2020 23:59  UTC
##########################################################

##########################################################
# LATI, Tirana (Albania)
# WMO index: 13615. WIGOS ID: 0-20000-0-13615
# Latitude 41-19-59N. Longitude 019-46-59E. Altitude 89 m.
##########################################################

# No METAR/SPECI reports frome LATI in database.

# No short TAF reports from LATI in databse.

###################################
#  large TAF from LATI
###################################
202007010500 TAF LATI 010500Z 0106/0206 VRB04KT CAVOK
                      TX35/0112Z TN20/0204
                      TEMPO 0109/0112 34012KT=
202007011100 TAF LATI 011100Z 0112/0212 34010KT CAVOK
                      TX35/0112Z TN20/0204Z
                      BECMG 0117/0119 VRB03KT=
202007011700 TA

In [ ]:
# Output of the function
clean_taf_ogimet_file('/content/TAF202007.txt')

                                           TAF Forecast
0     202007010500 TAF LATI 010500Z 0106/0206 VRB04K...
1     202007011100 TAF LATI 011100Z 0112/0212 34010K...
2     202007011700 TAF LATI 011700Z 0118/0218 VRB03K...
3     202007012300 TAF LATI 012300Z 0200/0224 VRB02K...
4     202007020500 TAF LATI 020500Z 0206/0306 VRB02K...
...                                                 ...
7769  202007310413 TAF AMD EGSS 310413Z 3104/0106 11...
7770  202007310459 TAF EGSS 310459Z 3106/0112 11010K...
7771  202007311103 TAF EGSS 311103Z 3112/0118 14013K...
7772  202007311702 TAF EGSS 311702Z 3118/0124 23010K...
7773  202007312307 TAF EGSS 312307Z 0100/0206 23008K...

[7774 rows x 1 columns]